# Generated by Django 5.2 on 2026-02-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userverification_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVerification',
        ),
    ]
