# Generated by Django 5.2 on 2026-02-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVerification',
        ),
    ]
