# Generated by Django 5.2 on 2026-02-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_message_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_author_box_maker',
            field=models.BooleanField(default=False),
        ),
    ]
