# Generated by Django 5.2 on 2026-02-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_message_is_author_box_maker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
