# Generated by Django 5.2 on 2026-01-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_box_created_at_box_updated_at_message_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
