# Generated by Django 5.2 on 2026-01-13 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_thread_delete_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_box',
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.thread'),
            preserve_default=False,
        ),
    ]
