# Generated by Django 5.2 on 2026-01-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_message_message_box_message_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_author',
        ),
    ]
