# Generated by Django 5.2 on 2026-01-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_message_message_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
